### ISSUE TITLE
SciML Backend

### ISSUE THREAD

**Issue by kanav99** [MLH-Fellowship/0.3.1-team1-COVIDTravelPlanner#2]
Copying down some tutorials/documentations @avik-pal suggested for this -

* https://www.hindawi.com/journals/ijpde/2014/186437/
* http://epirecip.es/epicookbook/chapters/sir/julia
* https://diffeqflux.sciml.ai/dev/examples/NN-ODE/

The dataset - https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by avik-pal** [comment]
This is not the final model we used. #9 takes precedence and solves this.
